### PR TITLE
Depend package refactors pt.1

### PR DESCRIPTION
**Pull request by NobleMathews**
- Exposes a `Depend` class for invocation from depend.core
- Rearranges a few of the functions for further creation of classes
  - Currently plan to introduce a `RequestHandler` class for cleaning up API logic, `DependVerConstraint` for pythonic conversion and a `Resolver` class for background workflow
  - Since this takes significant refactors will do it in subsequent pulls
  - Will add detailed docs and update documentation once all of the above is completed

### CODE REVIEW

**Comment by tushar-deepsource** [comment]
@NobleMathews what's the status on this?

**Comment by NobleMathews** [comment]
> @NobleMathews what's the status on this?

Didn't see the tests failed will fix them in a few

**Comment by tushar-deepsource** [comment]
Small suggestion, can you move the `handle_dep_file` logic to a `DependencyParser` class as well? It's alright if you do it in this PR or another PR.

**Comment by tushar-deepsource** [comment]
I think you removed the `debug` toggle altogether, and it's debug by default now. `loop.set_debug = True` should only be done when `--debug` is passed.

**Review by tushar-deepsource — APPROVED** [review]

**Pull request merged**
